# Generated by Django 4.2.1 on 2023-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Мой блог',
                'verbose_name_plural': 'Мой блог',
                'ordering': ['id'],
            },
        ),
    ]
