# Generated by Django 4.2.1 on 2023-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogform_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogform',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
